version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./templates:/etc/nginx/templates
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=domain_name.com
      - NGINX_PORT=80
      - NGINX_BUCKET_HOST=s3-ap-southeast-1.amazonaws.com
    command: [ nginx-debug, '-g', 'daemon off;' ]
